// Placeholder JSON — swap for real API when backend is ready

export const ITEMS_PLACEHOLDER = [
    {
        id: '1',
        title: 'Canon EOS R5 Camera',
        description: 'Professional full-frame mirrorless camera. Perfect for events, portraits, and cinematic videography. Comes with a 24–105mm lens, extra batteries, and a carry case.',
        pricePerDay: 1500,
        category: 'Creative & Media Gear',
        location: 'Bandra, Mumbai',
        distance: 0.5,
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=700&q=80',
        ownerName: 'Varad Kulkarni',
        ownerAvatar: 'https://i.pravatar.cc/80?img=12',
        rating: 4.9,
        reviewCount: 34,
        available: true,
        availableFrom: '2026-03-01',
        availableTo: '2026-03-31',
    },
    {
        id: '2',
        title: 'Power Drill & Tool Kit',
        description: 'Bosch 18V cordless drill with a full 40-piece bit set. Ideal for home renovation, shelving, and small construction work.',
        pricePerDay: 200,
        category: 'Professional Equipment',
        location: 'Andheri, Mumbai',
        distance: 1.2,
        image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=700&q=80',
        ownerName: 'Priya Sharma',
        ownerAvatar: 'https://i.pravatar.cc/80?img=5',
        rating: 4.7,
        reviewCount: 22,
        available: true,
        availableFrom: '2026-03-01',
        availableTo: '2026-04-15',
    },
    {
        id: '3',
        title: '4-Person Camping Tent',
        description: 'Lightweight waterproof tent with UV protection. Sets up in 10 minutes. Great for weekend treks and outdoor adventures.',
        pricePerDay: 400,
        category: 'Outdoor & Adventure',
        location: 'Powai, Mumbai',
        distance: 3.0,
        image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=700&q=80',
        ownerName: 'Arjun Mehta',
        ownerAvatar: 'https://i.pravatar.cc/80?img=33',
        rating: 4.8,
        reviewCount: 18,
        available: true,
        availableFrom: '2026-03-05',
        availableTo: '2026-03-25',
    },
    {
        id: '4',
        title: 'Electric Scooter',
        description: 'Ather 450X electric scooter with 100km range. Helmet included. Suitable for city commutes and short-distance rides.',
        pricePerDay: 600,
        category: 'Mobility & Transport',
        location: 'Juhu, Mumbai',
        distance: 0.9,
        image: 'https://images.unsplash.com/photo-1597404294360-feed936f67f8?auto=format&fit=crop&w=700&q=80',
        ownerName: 'Sneha Patil',
        ownerAvatar: 'https://i.pravatar.cc/80?img=47',
        rating: 4.6,
        reviewCount: 41,
        available: true,
        availableFrom: '2026-03-01',
        availableTo: '2026-05-01',
    },
    {
        id: '5',
        title: 'JBL PartyBox Speaker',
        description: 'Powerful Bluetooth party speaker with 100W output, light effects, and 18-hour battery. Perfect for events, birthdays, and rooftop parties.',
        pricePerDay: 750,
        category: 'Event & Party Gear',
        location: 'Dadar, Mumbai',
        distance: 2.5,
        image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=700&q=80',
        ownerName: 'Rahul Joshi',
        ownerAvatar: 'https://i.pravatar.cc/80?img=70',
        rating: 5.0,
        reviewCount: 57,
        available: false,
        availableFrom: '2026-03-15',
        availableTo: '2026-04-30',
    },
    {
        id: '6',
        title: 'Trek Mountain Bike',
        description: 'Trek 29-er mountain bike with hydraulic disc brakes, 21 speeds, and front suspension. Well-maintained. Helmet and lock included.',
        pricePerDay: 350,
        category: 'Fitness & Sports',
        location: 'Goregaon, Mumbai',
        distance: 4.1,
        image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=700&q=80',
        ownerName: 'Kavya Nair',
        ownerAvatar: 'https://i.pravatar.cc/80?img=29',
        rating: 4.5,
        reviewCount: 14,
        available: true,
        availableFrom: '2026-03-01',
        availableTo: '2026-03-31',
    },
    {
        id: '7',
        title: 'DJI Mini 3 Drone',
        description: 'Compact 4K/60fps drone with 34-min flight time and obstacle sensing. Great for aerial photography and real estate tours.',
        pricePerDay: 1200,
        category: 'Creative & Media Gear',
        location: 'Versova, Mumbai',
        distance: 2.0,
        image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=700&q=80',
        ownerName: 'Karan Desai',
        ownerAvatar: 'https://i.pravatar.cc/80?img=61',
        rating: 4.9,
        reviewCount: 26,
        available: true,
        availableFrom: '2026-03-02',
        availableTo: '2026-04-20',
    },
    {
        id: '8',
        title: 'MacBook Pro 16"',
        description: 'M3 Pro chip, 18GB RAM, 512GB SSD. Loaded with Adobe Suite, Final Cut Pro, and Xcode. Perfect for editing, development, or presentations.',
        pricePerDay: 1800,
        category: 'Tech & Gadgets',
        location: 'Lower Parel, Mumbai',
        distance: 3.5,
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=700&q=80',
        ownerName: 'Nisha Singh',
        ownerAvatar: 'https://i.pravatar.cc/80?img=9',
        rating: 4.8,
        reviewCount: 19,
        available: true,
        availableFrom: '2026-03-01',
        availableTo: '2026-03-20',
    },
];

export const CATEGORIES = [
    'Everyday Essentials',
    'Tech & Gadgets',
    'Home & Living',
    'Mobility & Transport',
    'Event & Party Gear',
    'Professional Equipment',
    'Outdoor & Adventure',
    'Fitness & Sports',
    'Study & Work Setup',
    'Creative & Media Gear',
];
